FROM ubuntu:18.04

# Tools
RUN apt-get update && apt-get install -y -V \
    apt-transport-https \
    g++ \
    git \
    lsb-release \
    pkg-config \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Go installation
RUN cd /tmp && \
    wget https://dl.google.com/go/go1.12.1.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.12.1.linux-amd64.tar.gz
ENV PATH="/usr/local/go/bin:${PATH}"

# Apache arrow
RUN wget -O /usr/share/keyrings/apache-arrow-keyring.gpg https://dl.bintray.com/apache/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-keyring.gpg
RUN echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/apache-arrow-keyring.gpg] https://dl.bintray.com/apache/arrow/ubuntu/ bionic main' >> /etc/apt/sources.list.d/apache-arrow.list
RUN echo 'deb-src [signed-by=/usr/share/keyrings/apache-arrow-keyring.gpg] https://dl.bintray.com/apache/arrow/ubuntu/ bionic main' >> /etc/apt/sources.list.d/apache-arrow.list
RUN apt update
RUN apt install -y -V libarrow-dev 

WORKDIR /carrow
COPY . .
RUN make
RUN go test -v ./...
