version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: make circleci
notify:
  webhooks:
    - url: https://353.zulipchat.com/api/v1/external/circleci?api_key=DnqIzcuzOZ0ujTmrcLdgfoSmEctALDgJ&stream=carrow&topic=circleci
